package com.macc.timesheet.presentation.model

data class EmployeeModel(
    val idEmpleado: Int = -1,
    val idArea: Int? = null,
    val idDepartamento: Int? = null,
    val idSubarea: Int? = null,
    val idPuesto: Int? = null,
    val idCedis: Int? = null,
    val claveContable: String? = null,
    val nombre: String? = null,
    val apellidoPaterno: String? = null,
    val apellidoMaterno: String? = null,
    val calle: String? = null,
    val numero: String? = null,
    val colonia: String? = null,
    val ciudad: String? = null,
    val estado: String? = null,
    val codigoPostal: String? = null,
    val correo: String? = null,
    val telefono: String? = null,
    val rfc: String? = null,
    val curp: String? = null,
    val imss: String? = null,
    val idTipoEmpleado: String? = null,
    val usuario: String? = null,
    val contrasenia: String? = null,
    val limiteCredito: Double? = null,
    val fechaRegistro: String? = null,
    val usuarioRegistro: Int? = null,
    val usuarioModifico: Int? = null,
    val activo: Boolean = true,
    val entradaMatutina: String? = null,
    val entradaVespertina: String? = null,
    val idEmpresa: Int? = null,
    val puesto: String? = null,
    val cedis: String? = null,
    val area: String? = null,
    val departamento: String? = null,
    val nombreCompleto: String = ""
)
